
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DIVIDE LPAREN MINUS NUMBER OTHE PLUS RPAREN TIMES\n    expression : expression PLUS term\n                | expression PLUS error\n    \n    expression : expression MINUS term\n                | expression MINUS error \n    expression : termterm : term TIMES factorterm : term DIVIDE factorterm : factorfactor : NUMBERfactor : OTHE\n    factor : LPAREN expression RPAREN\n    '
    
_lr_action_items = {'NUMBER':([0,6,7,8,9,10,],[4,4,4,4,4,4,]),'OTHE':([0,6,7,8,9,10,],[5,5,5,5,5,5,]),'LPAREN':([0,6,7,8,9,10,],[6,6,6,6,6,6,]),'$end':([1,2,3,4,5,12,13,14,15,16,17,18,],[0,-5,-8,-9,-10,-1,-2,-3,-4,-6,-7,-11,]),'PLUS':([1,2,3,4,5,11,12,13,14,15,16,17,18,],[7,-5,-8,-9,-10,7,-1,-2,-3,-4,-6,-7,-11,]),'MINUS':([1,2,3,4,5,11,12,13,14,15,16,17,18,],[8,-5,-8,-9,-10,8,-1,-2,-3,-4,-6,-7,-11,]),'RPAREN':([2,3,4,5,11,12,13,14,15,16,17,18,],[-5,-8,-9,-10,18,-1,-2,-3,-4,-6,-7,-11,]),'TIMES':([2,3,4,5,12,14,16,17,18,],[9,-8,-9,-10,9,9,-6,-7,-11,]),'DIVIDE':([2,3,4,5,12,14,16,17,18,],[10,-8,-9,-10,10,10,-6,-7,-11,]),'error':([7,8,],[13,15,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,6,],[1,11,]),'term':([0,6,7,8,],[2,2,12,14,]),'factor':([0,6,7,8,9,10,],[3,3,3,3,16,17,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression PLUS term','expression',3,'p_expression_plus','test_parser.py',10),
  ('expression -> expression PLUS error','expression',3,'p_expression_plus','test_parser.py',11),
  ('expression -> expression MINUS term','expression',3,'p_expression_minus','test_parser.py',25),
  ('expression -> expression MINUS error','expression',3,'p_expression_minus','test_parser.py',26),
  ('expression -> term','expression',1,'p_expression_term','test_parser.py',33),
  ('term -> term TIMES factor','term',3,'p_term_times','test_parser.py',37),
  ('term -> term DIVIDE factor','term',3,'p_term_div','test_parser.py',41),
  ('term -> factor','term',1,'p_term_factor','test_parser.py',45),
  ('factor -> NUMBER','factor',1,'p_factor_num','test_parser.py',49),
  ('factor -> OTHE','factor',1,'p_factor_othe','test_parser.py',54),
  ('factor -> LPAREN expression RPAREN','factor',3,'p_factor_expr','test_parser.py',60),
]
