repos:
  - repo: https://github.com/Lucas-C/pre-commit-hooks.git
    rev: v1.5.5
    hooks:
      - id: remove-crlf
        files: (?!.*third_party)^.*$ | (?!.*book)^.*$
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args:
          - --maxkb=20480
      - id: check-merge-conflict
      - id: check-symlinks
      - id: detect-private-key
        files: (?!.*third_party)^.*$ | (?!.*book)^.*$
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: requirements-txt-fixer
      - id: sort-simple-yaml

  - repo: https://gitee.com/dnguyen/cmake-pre-commit-hooks-mirror
    rev: v1.5.3
    hooks:
      # -   id: clang-format
      #     require_serial: false
      #     args: [-i]
      #     files: .*\.(h|hpp|tpp|cpp|cc)$
      #     additional_dependencies: [clang-format==14.*]
      # -   id: cpplint
      #     require_serial: false
      #     args: [--quiet]
      #     files: .*\.(h|hpp|tpp|cpp|cc)$
      #     additional_dependencies: [cpplint]
      - id: lizard
        require_serial: false
        # files: .*\.(h|hpp|tpp|cpp|cc|py)$
        files: .*\.(h|hpp|tpp|cpp|cc)$
        args:
          [
            -l,
            cpp,
            -l,
            python,
            -l,
            java,
            -C,
            "19",
            -L,
            "100",
            -x,
            "*/tests/*",
            -x,
            "*/test/*",
            -x,
            "*/third_party/*",
            -W.whitelizard.txt,
            -w,
          ]
        additional_dependencies:
          [lizard]
          #     - id: clang-tidy
          #       stages: [manual]
          #       args: [-Bbuild, -B.pre-commit-build]
          #       exclude: >-
          #         (?x)^(
          #           .*/kernel[0-9]+\.hpp|
          #           .*third_party/.*|
          #           .*\.cu
          #         )$

          # TODO: Ignore cpp file check.
          # -   repo: https://gitee.com/btcong/pre-commit-hooks
          #     rev: v1.3.5
          #     hooks:
          #     -   id: cppcheck
          #         files: .*\.(h|hpp|tpp|cpp|cc)$
          #         args: [--force, --enable=all, --error-exitcode=1, --inline-suppr, --std=c++14, --language=c++, --suppressions-list=.cppcheck.suppressions]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.0
    hooks:
      # Run the linter.
      - id: ruff-check
        exclude: examples/.*
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
        exclude: examples/.*
