repos:
-   repo: https://github.com/Lucas-C/pre-commit-hooks.git
    rev: v1.5.5
    hooks:
    -   id: remove-crlf
        files: (?!.*third_party)^.*$ | (?!.*book)^.*$
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-added-large-files
        args:
        -   --maxkb=20480
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: detect-private-key
        files: (?!.*third_party)^.*$ | (?!.*book)^.*$
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: requirements-txt-fixer
    -   id: sort-simple-yaml

-   repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks.git
    rev: v2.14.0
    hooks:
    -   id: pretty-format-yaml
        args: [--autofix, --indent, '4']
-   repo: https://github.com/hadialqattan/pycln
    rev: v2.4.0
    hooks:
    -   id: pycln
  # -   repo: https://github.com/pre-commit/mirrors-clang-format
  #     rev: v15.0.7
  #     hooks:
  #     -   id: clang-format
  #         args: [-style=file]
  # Using this mirror lets us use mypyc-compiled black, which is about 2x faster
-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.10.0
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
    -   id: isort
        name: isort (python)
        args: [--profile, black, --filter-files]

-   repo: https://gitee.com/dnguyen/cmake-pre-commit-hooks-mirror
    rev: v1.5.3
    hooks:
      # -   id: clang-format
      #     require_serial: false
      #     args: [-i]
      #     files: .*\.(h|hpp|tpp|cpp|cc)$
      #     additional_dependencies: [clang-format==14.*]
      # -   id: cpplint
      #     require_serial: false
      #     args: [--quiet]
      #     files: .*\.(h|hpp|tpp|cpp|cc)$
      #     additional_dependencies: [cpplint]
    -   id: lizard
        require_serial: false
        files: .*\.(h|hpp|tpp|cpp|cc|py)$
        args: [-l, cpp, -l, python, -l, java, -C, '19', -L, '100', -x, '*/tests/*', -x, '*/test/*', -x, '*/third_party/*', -W.whitelizard.txt, -w]
        additional_dependencies: [lizard]
    #     - id: clang-tidy
    #       stages: [manual]
    #       args: [-Bbuild, -B.pre-commit-build]
    #       exclude: >-
    #         (?x)^(
    #           .*/kernel[0-9]+\.hpp|
    #           .*third_party/.*|
    #           .*\.cu
    #         )$

  # TODO: Ignore cpp file check.
  # -   repo: https://gitee.com/btcong/pre-commit-hooks
  #     rev: v1.3.5
  #     hooks:
  #     -   id: cppcheck
  #         files: .*\.(h|hpp|tpp|cpp|cc)$
  #         args: [--force, --enable=all, --error-exitcode=1, --inline-suppr, --std=c++14, --language=c++, --suppressions-list=.cppcheck.suppressions]

-   repo: https://gitee.com/mirrors/flake8
    rev: 5.0.4
    hooks:
    -   id: flake8
        args: [--docstring-convention, google]
        name: flake8-strict
        exclude: (.*_test\.py)$
        additional_dependencies: [flake8-breakpoint, flake8-builtins, flake8-comprehensions, flake8-continuation, flake8-docstrings, flake8-eradicate, flake8-mutable, flake8-return, pep8-naming, flake8-secure-coding-standard]
    -   id: flake8
        name: flake8-test-files
        files: (.*_test\.py)$
        additional_dependencies: [flake8-breakpoint, flake8-builtins, flake8-comprehensions, flake8-continuation, flake8-eradicate, flake8-mutable, flake8-return]
